//------------------------------------------------------------------------------
// <auto-generated>
//     Mã này được tạo ra bởi một công cụ.
//     Phiên bản Runtime: 4.0.30319.42000
//
//     Các thay đổi vào tệp này có thể gây ra hành vi không chính xác và sẽ bị mất nếu
//     mã được tạo lại.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniSupermarket.Properties
{
    using System;


    /// <summary>
    ///   Một lớp tài nguyên có kiểu mạnh, dùng để tra cứu các chuỗi cục bộ, v.v.
    /// </summary>
    // Lớp này được tạo ra tự động bởi công cụ StronglyTypedResourceBuilder
    // thông qua một công cụ như ResGen hoặc Visual Studio.
    // Để thêm hoặc xóa một thành viên, hãy chỉnh sửa tệp .ResX của bạn sau đó chạy lại ResGen
    // với tùy chọn /str, hoặc xây dựng lại dự án VS của bạn.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:Tránh việc sử dụng mã chưa sử dụng")]
        internal Resources()
        {
        }

        /// <summary>
        ///   Trả về trường ResourceManager được lưu trữ để sử dụng bởi lớp này.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MiniSupermarket.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Ghi đè thuộc tính CurrentUICulture của luồng hiện tại cho tất cả
        ///   tra cứu tài nguyên sử dụng lớp tài nguyên kiểu mạnh này.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Tra cứu một tài nguyên cục bộ có kiểu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap add
        {
            get
            {
                object obj = ResourceManager.GetObject("add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Tra cứu một tài nguyên cục bộ có kiểu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap calendarDark
        {
            get
            {
                object obj = ResourceManager.GetObject("calendarDark", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Tra cứu một tài nguyên cục bộ có kiểu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap calendarWhite
        {
            get
            {
                object obj = ResourceManager.GetObject("calendarWhite", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Tra cứu một tài nguyên cục bộ có kiểu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap delete
        {
            get
            {
                object obj = ResourceManager.GetObject("delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Tra cứu một tài nguyên cục bộ có kiểu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap delete_document
        {
            get
            {
                object obj = ResourceManager.GetObject("delete_document", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Tra cứu một tài nguyên cục bộ có kiểu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap iconProduct
        {
            get
            {
                object obj = ResourceManager.GetObject("iconProduct", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Tra cứu một tài nguyên cục bộ có kiểu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap iconX
        {
            get
            {
                object obj = ResourceManager.GetObject("iconX", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Tra cứu một tài nguyên cục bộ có kiểu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LoginLogo
        {
            get
            {
                object obj = ResourceManager.GetObject("LoginLogo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Tra cứu một tài nguyên cục bộ có kiểu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap maximize
        {
            get
            {
                object obj = ResourceManager.GetObject("maximize", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Tra cứu một tài nguyên cục bộ có kiểu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap miniMarketLogo3
        {
            get
            {
                object obj = ResourceManager.GetObject("miniMarketLogo3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Tra cứu một tài nguyên cục bộ có kiểu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap minimize
        {
            get
            {
                object obj = ResourceManager.GetObject("minimize", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Tra cứu một tài nguyên cục bộ có kiểu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap minus_button
        {
            get
            {
                object obj = ResourceManager.GetObject("minus_button", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Tra cứu một tài nguyên cục bộ có kiểu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap reloading
        {
            get
            {
                object obj = ResourceManager.GetObject("reloading", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Tra cứu một tài nguyên cục bộ có kiểu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap right_arrow
        {
            get
            {
                object obj = ResourceManager.GetObject("right-arrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Tra cứu một tài nguyên cục bộ có kiểu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap search
        {
            get
            {
                object obj = ResourceManager.GetObject("search", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Tra cứu một tài nguyên cục bộ có kiểu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap update
        {
            get
            {
                object obj = ResourceManager.GetObject("update", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
